### ISSUE TITLE
Как пользоваться?

### ISSUE THREAD

**Issue by dimakudos** [evgeek/moysklad#1]
Установка
$ composer require evgeek/moysklad

Это куда надо писать? Куда файлы копировать? В общем, очень непонятно описано и как пользоваться не понятно...

**Comment by evgeek** [comment]
В Readme описана установка пакета через командную строку Linux при помощи менеджера зависимостей [Composer](https://github.com/composer/composer. Это стандартный для PHP менеджер зависимостей, поэтому нюансы по его установке/настройке не включены в инструкцию. Очень советую разобраться с ним, если вы работаете с PHP. 
Помимо официальной документации на английском, есть понятные статьи и на русском с примерами - допустим, [эта](https://habr.com/ru/post/439200/) или [вот](https://habr.com/ru/post/145946/).
