### ISSUE TITLE
HELP!!!!

### ISSUE THREAD

**Issue by AlexJMcloud** [evgeek/moysklad#14]
Проблема!!! Составление запроса правильное, но при вызове метода get() - пустота! Где-то по пути теряются данные.

**Comment by AlexJMcloud** [comment]
Предыдущая версия работала нормально. Заметил сегодня, после обновления composer, что конструкция запроса другая.

**Comment by evgeek** [comment]
А покажите, пожалуйста, код проблемного запроса - проверю

**Comment by evgeek** [comment]
> Составление запроса правильное, но при вызове метода get() - пустота!

А покажите, пожалуйста, код проблемного запроса - проверю

**Comment by AlexJMcloud** [comment]
> > Составление запроса правильное, но при вызове метода get() - пустота!
> 
> А покажите, пожалуйста, код проблемного запроса - проверю
Авторизация через токен
$this->ms->query()->entity()->product()->byId($uid)->get();

**Comment by AlexJMcloud** [comment]
Что-то не не так с передачей токена. по паре - логин/пароль, запрос получен.
