### ISSUE TITLE
Сущности

### ISSUE THREAD

**Issue by AlexJMcloud** [evgeek/moysklad#15]
Теперь точно по существу. Работа с сущностями по типу - "companysettings/pricetype". Api отдает json. По коду я получаю вот такую ошибку:
Fatal error</b>:  Uncaught TypeError: Evgeek\Moysklad\Formatters\StdClassFormat::encode(): Return value must be of type stdClass, array returned in /vendor/evgeek/moysklad/src/Formatters/StdClassFormat.php:31
vendor/evgeek/moysklad/src/Http/ApiClient.php(39): Evgeek\Moysklad\Formatters\StdClassFormat::encode('[ {\n  &quot;meta&quot; : ...')vendor/evgeek/moysklad/src/Api/Builders/Builder.php(40): Evgeek\Moysklad\Http\ApiClient-&gt;send(Object(Evgeek\Moysklad\Http\Payload))vendor/evgeek/moysklad/src/Api/Traits/Actions/GetTrait.php(27): Evgeek\Moysklad\Api\Builders\Builder-&gt;apiSend(Object(Evgeek\Moysklad\Enums\HttpMethod))

**Comment by AlexJMcloud** [comment]
это я создаю товар на моемскладе.

**Comment by evgeek** [comment]
А можно тоже пример запроса?
Потому что просто создание товара, в духе `$ms->query()->entity()->product()->create(['name' => 'test'])` проходит успешно

**Comment by AlexJMcloud** [comment]
`$metaPrice = $this->ms->query()->endpoint('context')
            ->method('companysettings/pricetype')
            ->get();
        $currency = $this->ms->query()->entity()->method('currency')->get();
        unset($currency->rows[0]->meta->uuidHref);
        $salePrice = [
            'value' => (int)($product->price*100),
            'currency' => ['meta' => $currency->rows[0]->meta],
            "priceType" => ['meta' => $metaPrice[0]->meta]
        ];
        $product_data = [
            'name' => $product->pro_name,
            'article' => $product->pro_articular,
            'code' => (string)$product->pro_id,
            'description' => 'site',
            'salePrices' => [$salePrice]
        ];
        $create = $this->ms->query()->entity()->product()->create($product_data);
        if($create)
        {

            $uids = $create->id;
            $this->model->addUidModif([
                    'moy_id' => 'NULL',
                    'moy_product' => $product->pro_id,
                    'moy_modif' => 0,
                    'moy_uid' => $uids]
            );
            return true;
        }`

**Comment by AlexJMcloud** [comment]
это тело метода создания товара, если отсутствует на складе. В текущей задаче стоит еще создание модификаций.

**Comment by evgeek** [comment]
Ага, поправил ошибку. Проверьте, пожалуйста, всё ли теперь работает

**Comment by AlexJMcloud** [comment]
> Ага, поправил ошибку. Проверьте, пожалуйста, всё ли теперь работает

Ок. После обеда проверю.

**Comment by AlexJMcloud** [comment]
Что-то пошло не так.
Fatal error: Uncaught TypeError: Evgeek\Moysklad\Formatters\StdClassFormat::encode(): Return value must be of type stdClass, array returned. /vendor/evgeek/moysklad/src/Formatters/StdClassFormat.php on line 31

**Comment by AlexJMcloud** [comment]
![m1](https://user-images.githubusercontent.com/65539718/216322519-86114f0c-397b-4d3f-8875-0618a0259998.JPG)

**Comment by AlexJMcloud** [comment]
Съедает где-то первую квадратную скобку

**Comment by AlexJMcloud** [comment]
Full error:


Fatal error: Uncaught TypeError: Evgeek\Moysklad\Formatters\StdClassFormat::encode(): Return value must be of type stdClass, array returned in /var/www/stylebike_ru_usr/data/www/stylebike.ru/vendor/evgeek/moysklad/src/Formatters/StdClassFormat.php:31 Stack trace: #0 /var/www/stylebike_ru_usr/data/www/stylebike.ru/vendor/evgeek/moysklad/src/Http/ApiClient.php(39): Evgeek\Moysklad\Formatters\StdClassFormat::encode('[ {\n "meta" : ...') #1 /var/www/stylebike_ru_usr/data/www/stylebike.ru/vendor/evgeek/moysklad/src/Api/Builders/Builder.php(40): Evgeek\Moysklad\Http\ApiClient->send(Object(Evgeek\Moysklad\Http\Payload)) #2 /var/www/stylebike_ru_usr/data/www/stylebike.ru/vendor/evgeek/moysklad/src/Api/Traits/Actions/GetTrait.php(27): Evgeek\Moysklad\Api\Builders\Builder->apiSend(Object(Evgeek\Moysklad\Enums\HttpMethod)) #3 /var/www/stylebike_ru_usr/data/www/stylebike.ru/app/plugins/mysklad/controller/AdminMyskladController.php(232): Evgeek\Moysklad\Api\Builders\Methods\MethodCommon->get() #4 /var/www/stylebike_ru_usr/data/www/stylebike.ru/app/plugins/mysklad/controller/AdminMyskladController.php(211): app\plugins\mysklad\controller\AdminMyskladController->createProductMS(Object(stdClass)) #5 /var/www/stylebike_ru_usr/data/www/stylebike.ru/app/plugins/mysklad/controller/AdminMyskladController.php(112): app\plugins\mysklad\controller\AdminMyskladController->responde(11861, '', Object(stdClass)) #6 /var/www/stylebike_ru_usr/data/www/stylebike.ru/system/core/Request.php(266): app\plugins\mysklad\controller\AdminMyskladController->syncProduct() #7 /var/www/stylebike_ru_usr/data/www/stylebike.ru/system/core/Request.php(171): system\core\Request::load('app\\plugins\\mys...') #8 /var/www/stylebike_ru_usr/data/www/stylebike.ru/system/core/Request.php(103): system\core\Request::build() #9 /var/www/stylebike_ru_usr/data/www/stylebike.ru/system/core/Request.php(28): system\core\Request::prepareURI() #10 /var/www/stylebike_ru_usr/data/www/stylebike.ru/app/init.php(44): system\core\Request->__construct() #11 /var/www/stylebike_ru_usr/data/www/stylebike.ru/public/index.php(9): require_once('/var/www/styleb...') #12 {main} thrown in /var/www/stylebike_ru_usr/data/www/stylebike.ru/vendor/evgeek/moysklad/src/Formatters/StdClassFormat.php on line 31

**Comment by AlexJMcloud** [comment]
парсит он правильно.

**Comment by AlexJMcloud** [comment]
проблема скорее всего в Apiclient. Скорее всего там он где-то обращается как классу без проверки.

**Comment by evgeek** [comment]
А вы обновили библиотеку?
`composer update evgeek/moysklad`

**Comment by AlexJMcloud** [comment]
да

**Comment by evgeek** [comment]
Прошу прощения, моя вина - криво вылил релиз. Перезалил, попробуйте ещё раз, пожалуйста - сейчас всё точно должно заработать :)

**Comment by evgeek** [comment]
Нюанс - новый релиз вылился под той же версией, `0.6.2`. Композер может решить, что обновление не требуется - в таком случае придётся обновиться форсированно:
```bash
composer update --prefer-source evgeek/moysklad
```

**Comment by AlexJMcloud** [comment]
> Нюанс - новый релиз вылился под той же версией, `0.6.2`. Композер может решить, что обновление не требуется - в таком случае придётся обновиться форсированно:
> 
> ```shell
> composer update --prefer-source evgeek/moysklad
> ```

Да теперь все прогрузилось на склад.

**Comment by AlexJMcloud** [comment]
Спасибо за помощь. Такой момент, вы пробовали добавлять модификации к товару через api.? Я пока не совсем точно себе это представляю.

**Comment by evgeek** [comment]
Супер ) Спасибо за обратную связь

**Comment by AlexJMcloud** [comment]
Примеры у них в документации скудные на сей вопрос.

**Comment by evgeek** [comment]
> Такой момент, вы пробовали добавлять модификации к товару через api?

Что-то такое делал, но это было года полтора назад, ничего не помню :)
Дойду вечером до домашнего компа - попробую найти пример

**Comment by AlexJMcloud** [comment]
Спасибо.

**Comment by evgeek** [comment]
Примерно так:

```php
$chars = $ms->query()
    ->entity()
    ->method('variant')
    ->method('metadata')
    ->get();
$charId = $chars->characteristics[0]->id;

$ms->query()
    ->entity()
    ->method('variant')
    ->create([
        'name' => 'test2',
        'characteristics' => [[
            'id' => $charId,
            'value' => '66',
        ]],
        'product' => [
            'meta' => Meta::product('bde980ec-a33a-11ed-0a80-068500036642')
        ],
    ]);
```
