### ISSUE TITLE
Добавление банковских счетов к контрагенту

### ISSUE THREAD

**Issue by ArtemYurov** [evgeek/moysklad#17]
Добрый день! 
Хотелось бы какой-то более удобный и наглядный способ для обновления сущностей.
Сейчас процесс для добавления нового счета к контрагенту выглядит так:

```
$contragent = $ms->query()->entity()->method('counterparty')->limit(100)->filter(.....)->expand('accounts')->get()->rows[0];

$contragent->accounts = $ms->query()->entity()->method('counterparty')->byId($contragent->id)->method('accounts')->get();

$contragent->accounts->rows[] = ['accountNumber' => $number, 'bankName' => $bankname, 'bic' => $bic];

$contragent = $ms->query()->entity()->method('counterparty')->byId($counterparty->id)->update($contragent);
```

Из самого очевидного - зачем нам ещё раз формировать url запроса к сущности, если он у нас лежит в meta->url? хотелось бы просто взять его и отправить запрос либо напрямую от сущности типа $contragent->update()
Либо, что могло бы пригодиться при работе со всякими доп справочниками и доп полями - обращение по url
типа $ms->queryByUrl($contragent->accounts->meta->url)->get()

**Comment by ArtemYurov** [comment]
До кучи, когда надо привязывать много meta для документа

```
        $payment = [....];
        $payment['organization'] = ['meta' => $organization->meta]; // или $payment['organization'] = ['meta' => Meta::organization($organization->id)];
        
        if ($organizationAccount) {
            $payment['organizationAccount'] = ['meta' => $organizationAccount->meta];
        }
        $payment['agent'] = ['meta' => $contragent->meta];
        if ($contragentAccount) {
            $payment['agentAccount'] = ['meta' => $contragentAccount->meta];
        }

       $payment = $this->moysklad->query()->entity()->method($method)->create($payment);

```

Тут было бы удобно иметь хелпер, который сразу вернет массив meta из сущности
$payment['organization'] = Meta::get($organization)
$payment['organization'] = $organization->getMeta()

**Comment by EvilDevRu** [comment]
Тут не хэлпер нужен а сущности. В ближ время реквест будет

**Comment by evgeek** [comment]
@EvilDevRu здравствуйте! Рад вашему участию :)

Я пока склоняюсь реализации извлечения меты из ответа именно через хелпер. Основная идея - иметь ответ от api в виде простого объекта/массива/строки, чтобы не пришлось привязывать каждую конкретную сущность к какому-то классу, т.к. это существенно усложнить поддержание библиотеки. Возможно, ваша идея лучше, но я её пока не понял. Присылайте PR, или, если хотите, можем обсудить заранее. Только обратите, пожалуйста, внимание - после вашего форка я релизнул v0.7.0, поэтому до старта разработки лучше обновиться по мастеру.

**Comment by EvilDevRu** [comment]
Да, уже видел. Можно обсудить, но у вас нет контактов. Без сущностей не знаешь с какими данными работаешь, можно запросто схватить ошибку, а так сущность еще и всех чилдов по цепочке создаст.

**Comment by evgeek** [comment]
[Телеграм](https://t.me/evgeek)

**Comment by evgeek** [comment]
@ArtemYurov добавил в v0.8.0 метод `fromUrl()`, описание добавил в [доку](https://github.com/evgeek/moysklad/blob/master/docs/query_builder.md#%D1%81%D0%B5%D0%B3%D0%BC%D0%B5%D0%BD%D1%82%D1%8B).

@EvilDevRu также реализовал возможность работы через [объекты](https://github.com/evgeek/moysklad/blob/master/docs/active_record.md). Похоже на желаемое? :)
