### ISSUE TITLE
Нужна документация по order()

### ISSUE THREAD

**Issue by ArtemYurov** [evgeek/moysklad#18]
->order('moment','desc') - так работает
->order('moment,desc') - так не использует порядок сортировки, отправляет как order=moment,desc,asc

Тогда вопрос, как указывать несколько сортировок? через массив?

**Comment by evgeek** [comment]
Можно так:

```php
$ms->query()
    ->entity()
    ->customerorder()
    ->order('updated')
    ->order('id', 'desc')
    ->get();
```

Либо, если есть желание в одну строку, так:

```php
$ms->query()
    ->entity()
    ->customerorder()
    ->param('order', 'updated,asc;id,desc')
    ->get();
```

Пример использования есть в пхпдоке:
![image](https://user-images.githubusercontent.com/93479789/217189641-2ab4fa62-a610-4e09-a806-9c4096f3d540.png)

В ридми в разделе про `param()` упоминается дозапись в `order` - но, вероятно, это недостаточно очевидно. Подумаю, как сделать понятнее. И заодно, про метод `orders` аналогично `filters`, чтобы задавать через массив
