### ISSUE TITLE
Подскажите по использованию

### ISSUE THREAD

**Issue by VasStepanov** [evgeek/moysklad#3]
Доброго дня! Библиотеку установил, классы подключаются, вроде все нормально, а вот как дальше - разобраться сложновато. 
Первый вопрос технический - будет ли работать на локалке (OpenServer) php 8.1 (просто может и не стоит на локалке пробовать, вот в чем вопрос, и все это работает только по https ?)
Но попробовал, вот так
```php
$ms = new \Evgeek\Moysklad\MoySklad(['my_token_here']);
$product = $ms->entity()->product()->limit(10);
```
получаю объект, но в нем по сути ничего нет, множество полей разных. Приведите пожалуйста какой то простейший пример, как получить, например, номер заказа, или контаргентов, ну то есть хоть увидеть работает или нет)) Дальше уже сам надеюсь разберусь. 
Заранее благодарен!

**Comment by evgeek** [comment]
Здравствуйте. На локалке работать будет, ssl-сертификат с вашей стороны не нужен :)

Касательно вашего примера - вы забыли добавить в конец цепочки вызовов http-метод отправки запроса (README.md, раздел 'Отправка запросов'). То есть, у вас "на руках" пока что конструктор запроса, а не ответ от API. Чтобы получить ответ, сделайте так:

```php
$ms = new \Evgeek\Moysklad\MoySklad(['my_token_here']);
$product = $ms->entity()->product()->limit(10)**->get()**;
```

**Comment by VasStepanov** [comment]
Евгений спасибо! Работает!  Извиняюсь за назойливость, но работает получается только product и assortment? Других классов, например counterparty, employee, project я не нашел. В библиотеке не предусмотрено или я что-то опять неправильно делаю?

**Comment by evgeek** [comment]
Отлично :)

Да, всё верно, полный список методов я ещё не реализовал. Чтобы работать с отсутствующими, вы можете:
* Использовать универсальные методы, такие, как `method()` (расписаны в Базовое использование -> Список универсальных методов). Так, допустим, запрос контрагентов будет выглядеть следующим образом:
```php
$counterparties = $ms->entity()->method('counterparty')->get();
```
Универсальными методами можно собрать буквально любой запрос.
* Реализовать нужные методы самостоятельно, по аналогии с имеющимися. Логику писать не надо - сами классы фактически пустые, требуется только изучить документацию Моего Склада по нужной сущности, и накидать согласно ей в новый класс уже написанные трейты, которые дадут новой сущности нужные методы. Не особо сложно, скорее, муторно. Если пойдёте по этому пути - присылайте мерж реквест, я проверю и добавлю.
* Поставить репозиторию звёздочку и рассчитывать, что внезапно пришедшая популярность заставит меня дописать нужные методы :)

**Comment by VasStepanov** [comment]
Все супер, спасибо! Звезда поставлена! Что со временем допишите остальное, думаю рассчитываю не только я))

**Comment by VasStepanov** [comment]
Евгений добрый день, прошу простить за назойливость, есть такой вопрос, делаю вот так:
```php
$customerorder = $ms->entity()
                                   ->customerorder()
                                   ->byId('order_id_here')
                                   ->expand('agent')
                                   ->expand('state')
                                   ->get();
```
развернутый объект agent' я получаю, а вот state не разворачивается, возможно потому, что state есть внутри agent ? Если отдельно развернуть state, не разворачивая agent, то все норм. Возможно есть какое то решение?

**Comment by evgeek** [comment]
Проверил - у меня разворачиваются оба одновременно.
![phpstorm64_AFpT6V9hQD](https://user-images.githubusercontent.com/93479789/176142420-aaa340a5-0ccd-4b24-b299-c2b3fa23e30c.png)

Можно перед `->get()` добавить `->debug()` - тогда вернёт отладочный объект, показывающий, как именно планируется послать запрос. Возьмите из поля `url` ссылку и попробуйте выполнить запрос вручную - через браузер, или через Postman какой-нибудь. Если результат будет тем же самым - тут лучше уже у поддержки Моего Склада спросить.
Возможно, у них есть какой-то лимит на размер возвращаемого объекта. Правда, в [документации ](https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api-obschie-swedeniq-zamena-ssylok-ob-ektami-s-pomosch-u-expand)у них написано только про ограничения expand на выборку 100+ объектов, и на вложенность 3+, т.е. проблем быть не должно.
