### ISSUE TITLE
Поменять url с online.moysklad.ru на api.moysklad.ru

### ISSUE THREAD

**Issue by deonoize** [evgeek/moysklad#32]
Привет, МойСклад поменял url с online.moysklad.ru на api.moysklad.ru.
Подробнее [тут](https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api-obschie-swedeniq-rekomendacii-po-pereezdu-na-nowyj-domen).

**Comment by evgeek** [comment]
Привет. Ага, спасибо. Они ещё и сжатие добавили :)
Изучу, добавлю. Пока оставлю тред открытым

**Comment by evgeek** [comment]
Внёс изменения, новый эндпойнт доступен с версии [v0.9.0](https://github.com/evgeek/moysklad/pull/33)

**Comment by vodnicearv** [comment]
в документации тоже нужно поправить, если смогу в выходные сделаю pull request
