### ISSUE TITLE
Изменения в классе Meta

### ISSUE THREAD

**Issue by deonoize** [evgeek/moysklad#38]
Привет!

В версии 0.10 появилось много изменений в классе `Meta`, есть пара моментов с ними:
1) Поменялся порядок аргументов в методе `state`, но об этом нет информации в Upgrade guide, а также нет примера в документации, как правильно передавать родителя.
2) В методе `attributemetadata`, используется только для сущности модификации, хотя атрибуты также есть у CustomerOrder например.

**Comment by evgeek** [comment]
Здравствуйте!
Формат `Meta::state()` поменялся в [v0.8.0](https://github.com/evgeek/moysklad/blob/master/UPGRADE.md#v080-changelog), в апгрейд гайде это упомянуто.
Про документацию - подробно формат для родителя расписан в [документации Record](https://github.com/evgeek/moysklad/blob/master/docs/active_record.md#%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8). Но согласен, это не очевидно, добавил в [доку Меты](https://github.com/evgeek/moysklad/blob/master/docs/tools.md#%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8) ссылку и пример.

С `attributemetadata` сложнее всего. Формат ссылки и ответа в модификациях отличается от формата в прочих сущностях. А в библиотека реализована по принципу "один тип - один путь - один формат". Так что пока что я вообще выпилил  `attributemetadata`, когда руки дойдут сделать под него какую-то отдельную логику - верну.

Спасибо за обратную связь :)

**Comment by deonoize** [comment]
Понял, спасибо :)
