### ISSUE TITLE
Что-то со свойствами класса не то ))

### ISSUE THREAD

**Issue by TemKaSD** [evgeek/moysklad#40]
Здравствуйте. Список товаров я получил.

`$products = $ms->query()
    ->entity()
    ->product()
    ->order('name')
    ->limit(3)
    ->get();`

Тут выдает предупреждение:
`foreach ($products as $product) {
    var_dump($product->name);
}`

> Warning: Undefined property: stdClass::$name in /moysklad/index.php on line 20 NULL

**Comment by evgeek** [comment]
Здравствуйте.

Мой Склад возвращает массив объектов ответа в поле `rows`, то есть итерация должна выглядеть следующим образом:

```php
foreach ($products->rows as $product) {
    var_dump($product->name);
}
```

А если нужно проитерировать всю коллекцию, можно использовать генератор, там `rows` не требуется:
```php
$products = $ms->query()->entity()->product()->order('name')->limit(3)->getGenerator();

foreach ($products as $product) {
    var_dump($product->name);
}
```
