### ISSUE TITLE
Цену возвращает в INT а не float

### ISSUE THREAD

**Issue by TemKaSD** [evgeek/moysklad#41]
Здравствуйте. Почему цену возвращает без плавающей точки?

![image](https://github.com/evgeek/moysklad/assets/6318282/e31b2450-ba3f-4d7f-a12e-0aa02e8496c1)

Тут должно быть 800,00

**Comment by evgeek** [comment]
Добрый день.
Мой Склад возвращает цены * 100, чтобы не было ошибок с плавающей точкой при расчёте копеек. Однако, я полагаю, если вы посмотрите тип value, там будет double. И это валидно, поскольку МС возвращает не 80000, а 80000.0

Касательно этого вопроса и соседнего - попробуйте сначала вручную отправить запрос к МС (для гет-запросов можно просто через браузер) и изучите ответ. Библиотека ответы никак не преобразует, только форматирует. Если надёте расхождение между МС и библиотекой - пишите :)
