### ISSUE TITLE
Expand Images

### ISSUE THREAD

**Issue by TemKaSD** [evgeek/moysklad#42]
Здравствуйте. expand() должен разворачивать картинки и возвращать в виде массива или что? с expand('images') и без него, результат один.

![image](https://github.com/evgeek/moysklad/assets/6318282/253cfac5-8cc9-4238-b56d-7ef7cf0f292d)

**Comment by evgeek** [comment]
Здравствуйте. expand работает с limit не более 100
https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api-obschie-swedeniq-zamena-ssylok-ob-ektami-s-pomosch-u-expand
