### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by Larionov-Andrey** [evgeek/moysklad#43]
Добрый день!
может ли библиотека работать с вебхуками?
Если да, то можно примеры?

**Comment by evgeek** [comment]
Здравствуйте. Библиотека может отправлять любые запросы к API Моего Склада.

Пример создания вебхука:

```php
$ms->query()->entity()->webhook()->create([
    "url" => "http://www.example.com",
    "action" => "CREATE",
    "entityType" => "service"
]);
```

Больше примеров работы с вебхуками вы можете найти в документации [МоегоСклада](https://dev.moysklad.ru/doc/api/remap/1.2/workbook/#workbook-vebhuki). Логика работы с библиотекой расписана в [её документации](https://github.com/evgeek/moysklad/blob/master/docs/index.md).
