### ISSUE TITLE
Запрос документа с остатками

### ISSUE THREAD

**Issue by bugaenkoleonid** [evgeek/moysklad#44]
Пытаюсь получить остаток для отгрузки, но не получается сформировать запрос тк operation.id заменяется на operation_id в конструкторе

Помогите

```
 $demandstock = $ms
->query()
->fromUrl("https://online.moysklad.ru/api/remap/1.2/report/stock/byoperation?operation.id=0bf54c31-9d12-11ee-0a80-153f00149905", true)
->get();
```

**Comment by evgeek** [comment]
Здравствуйте. Действительно, есть такое, неожиданно :)
[Поправил](https://github.com/evgeek/moysklad/pull/45) в [v0.11.1](https://github.com/evgeek/moysklad/releases/tag/v0.11.1)
