### ISSUE TITLE
Как получить количество продаж каждого товара?

### ISSUE THREAD

**Issue by Just-guy** [evgeek/moysklad#47]
Здравствуйте, поступила задача получить количество продаж каждого товара. Необходимую мне информацию нашел в разделе «История» у каждого товара. Скажите, через какой метод я могу получить историю или может у вас уже есть метод который сможет мне предоставить информацию о количестве проданных товаров?
![мойсклад1](https://github.com/evgeek/moysklad/assets/62421873/b92d0554-f339-4cca-9e4c-50e835a1333a)

**Comment by evgeek** [comment]
Добрый день.
Вопросы по API лучше задавать поддержке Моего Склада, они в этом лучше разбираются :) А в библиотеке нужные методы точно есть.
Но, навскидку, вам проще будет зайти через заказы - https://dev.moysklad.ru/doc/api/remap/1.2/documents/#dokumenty-zakaz-pokupatelq-poluchit-spisok-zakazow-pokupatelej. Не уверен, что история есть в API.
Парсите заказы, там есть позиции, позиции ассоциируются с товарами и содержат количество. Несложным агрегирующим запросом получаете суммарные продажи по товарам.

**Comment by Just-guy** [comment]
Доброе утро, спасибо за идею, сегодня обязательно попробую. Isuue не закрывайте пока, если найду решение обязательно опубликую тут.

**Comment by Just-guy** [comment]
Продолжаю работать над задачей, спасибо вам за библиотеку! Есть одна неопределенность...
Вот я вручную делаю запрос через API моегоСклада https://api.moysklad.ru/api/remap/1.2/report/profit/byproduct?filter=product=https://api.moysklad.ru/api/remap/1.2/entity/product/efabc0f3-ccc9-11e9-9ff4-3150004ee9d8&momentFrom=2019-01-01 и получаю данные по отчету «Прибыльность» одного товара:
![API МойСклад — результат по отчету прибыльностьi](https://github.com/evgeek/moysklad/assets/62421873/f2ae0741-c5f0-4d99-a660-d58cc08b6086)


Далее я сформировал такой же запрос через вашу библиотеку:
```php
	use Evgeek\Moysklad\MoySklad;
	$ms = new MoySklad(['token']);
	$product = $ms->query()
        ->endpoint('report')
        ->method('profit')
        ->method('byproduct')
	     ->param('filter=product', 'https://api.moysklad.ru/api/remap/1.2/entity/product/efabc0f3-ccc9-11e9-9ff4-3150004ee9d8')
	     ->param('momentFrom', '2019-01-01')
	         ->debug()
        ->send('GET');
``` 
Результат debug'a, url'ы идентичны:
![библиотека МойСклад — результат по отчету прибыльностьi](https://github.com/evgeek/moysklad/assets/62421873/6fe3e255-38d9-49e2-9486-33301a4605b3)

Но вместо одного товара я получаю целый массив из 1000 товаров:
![image](https://github.com/evgeek/moysklad/assets/62421873/1ef8986f-552f-466a-834a-9c33e889db97)

**Comment by evgeek** [comment]
Здравствуйте! Нужный отчёт всё-таки нашёлся? Отлично :)

Касательно вашего вопроса - query-параметры в url формируются при помощи функции [http_build_query](https://www.php.net/manual/en/function.http-build-query.php), которая кодирует ключ и значение каждого параметра в формат URL (`url_encoded` в дебаге). В вашем случае ключом будет не `filter=product`, а `filter`, а параметром - `product=https://api.moysklad.ru/api/remap/1.2/entity/product/efabc0f3-ccc9-11e9-9ff4-3150004ee9d8`.

Чтобы было меньше путаницы, можно воспользоваться методом filter, примерно так:

```php
$product = $ms->query()
    ->report()
    ->method('profit')
    ->method('byproduct')
    ->filter('product', 'https://api.moysklad.ru/api/remap/1.2/entity/product/607da4da-0fea-11eb-0a80-009b0010f47d')
    ->param('momentFrom', '2019-01-01')
    ->get();
```

**Comment by evgeek** [comment]
Закрыто в связи с отсутствием активности
