### ISSUE TITLE
Поиск товара с нужными свойствами

### ISSUE THREAD

**Issue by bugaenkoleonid** [evgeek/moysklad#49]
Как найти все модификации для определенного цвета, например?

$variants = UnknownObject::collection($ms, ['entity', 'variant'], 'variant')
  ->filter('https://api.moysklad.ru/api/remap/1.2/entity/variant/metadata/characteristics/63567822-c3a4-11eb-0a80-001f0022de58', '=', "бежевый")
  ->get();

**Comment by evgeek** [comment]
Здравствуйте!
Судя по описанию API касательно [характеристик ](https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-harakteristiki-modifikacij) и [модификаций ](https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-modifikaciq), в один запрос - никак.
Поиск по модификациям доступен только по названию характеристики (`->search('бежевый')`), но не гарантирует, что будет найдена именно нужная модификация. Если цвета встречаются только в одном типе характеристик - этот вариант, в принципе, подойдёт.
Либо можно получить вообще все модификации, и отфильтровать их уже в коде
