### ISSUE TITLE
use meta->href

### ISSUE THREAD

**Issue by AlexJMcloud** [evgeek/moysklad#5]
Здравствуйте. У меня такой вопрос в рамках ваше проекта как я могу быстро переходить по адресам получаемым в meta.
Какой мне использовать для этого метод или писать свой?

**Comment by evgeek** [comment]
Здравствуйте!
Хорошая идея сделать какой-нибудь метод в духе `$ms->parseUrl(url: $product->rows[0]->meta)->get();`
Однако, сейчас такого, к сожалению, нет

**Comment by AlexJMcloud** [comment]
Спасибо. Решил сделать немного по другому.
