### ISSUE TITLE
Добавить в метод state класса Meta параметр entity

### ISSUE THREAD

**Issue by deonoize** [evgeek/moysklad#6]
Привет!
Заметил, что в классе `Meta` есть метод `state` и он возвращает метадату статуса только для заказа (_customerorder_). Думаю можно было бы добавить вторым параметром в этом методе переменную `entity`, со значением по умолчанию "_customerorder_". Это даст возможность создавать метадату статуса для любой сущности с помощью этого метода.

**Comment by evgeek** [comment]
Привет! Отличная идея :)
Сделал, только `customerorder` по умолчанию показался мне избыточным, так что при обновлении придётся его добавить в `Meta::state()` вручную.
